import { Inter } from "next/font/google";
import "./globals.css";
import {
  experimental_extendTheme as extendTheme,
  Experimental_CssVarsProvider as CssVarsProvider,
} from "@mui/material/styles";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <InitColorSchemeScript />
        <CssVarsProvider defaultMode="light">{children}</CssVarsProvider>
      </body>
    </html>
  );
}
